basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample blog platform API.
  title: Backend Takehome API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
